<?php

abstract class human {
    function consumeProtein() {
    }
}

class muscle extends human {
    function consumeProtein()
    {
        parent::consumeProtein(); // TODO: Change the autogenerated stub
    }
}
